name: Build and Deploy Multiple Sites

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.0'

      - name: Build portfolio-front
        run: |
          cd portfolio-front
          npm install
          ./node_modules/.bin/vite build

      - name: Build portfolio-coding
        run: |
          cd portfolio-coding
          npm install
          ./node_modules/.bin/vite build          

      - name: Build Motion-Palette
        run: |
          cd Motion-Palette
          npm install
          chmod +x ./node_modules/.bin/vite
          ./node_modules/.bin/vite build

      # - name: Build Free-game-ya-san
      #   run: |
      #     cd Free-game-ya-san
      #     npm install
      #     ./node_modules/.bin/vite build

      - name: Prepare deploy directory
        run: |
          mkdir deploy
          cp -r portfolio-coding/dist deploy/portfolio-coding
          cp -r portfolio-front/dist deploy/portfolio-front
          cp -r Motion-Palette/dist deploy/Motion-Palette
          mkdir -p deploy/Pixel-Art-App
          cp -r Pixel-Art-App/* deploy/Pixel-Art-App/

      - name: Deploy all sites
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
